### ISSUE TITLE
Multiple Exceptions: Windows 10 PS

### ISSUE THREAD

**Issue by FCDEV01** [officespacesoftware/ps_ad_emp_push#1]
Get-ADUser : Cannot validate argument on parameter 'LDAPFilter'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At \REALSERVERNAME\Redir\Documents\AUserName\Documents\AD-OFFICESPACESYNC.ps1:53 char:88
- ... UDNsSplit.count-2)] | foreach {Get-ADUser -LDAPFilter $filter -Search ...
-                                                           ~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Get-ADUser], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.GetADUser

Get-ADUser : Cannot validate argument on parameter 'LDAPFilter'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At \REALSERVERNAME\Redir\Documents\AUserName\Documents\AD-OFFICESPACESYNC.ps1:53 char:88
- ... UDNsSplit.count-2)] | foreach {Get-ADUser –LDAPAUserNameAUserName   Filter $filter -Search ...
-                                                           ~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Get-ADUser], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.ActiveDirectory.Management.Commands.GetADUser

Staging records...
Sending records to https://familycare.officespacesoftware.com/api/1/employee_batch_imports
Cannot index into a null array.
At \REALSERVERNAME\Redir\Documents\AUserName\Documents\AD-OFFICESPACESYNC.ps1:68 char:25
- foreach ($ADuserinOU in $ADusersinOU[$start..$end])
-                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : NullArray

Exception calling "GetBytes" with "1" argument(s): "Array cannot be null.
Parameter name: chars"
At \REALSERVERNAME\Redir\Documents\AUserName\Documents\AD-OFFICESPACESYNC.ps1:108 char:3
-   $JSONArrayUTF8 = [System.Text.Encoding]::UTF8.GetBytes($JSONArray)
-   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ArgumentNullException

1-1000 The remote server returned an error: (500) Internal Server Error.
Triggering migration
Invoke-WebRequest : {"response":{"error":"Unknown Source: ActiveDirectory"}}
At \REALSERVERNAME\Redir\Documents\AUserName\Documents\AD-OFFICESPACESYNC.ps1:127 char:1
- Invoke-WebRequest -Uri $employee_import_url -Method Post -Body $impor ...
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
  - FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
    Completed

---

PSVersion                      5.0.10240.17113  
WSManStackVersion              3.0  
SerializationVersion           1.1.0.1  
CLRVersion                     4.0.30319.42000  
BuildVersion                   10.0.10011.16384  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}  
PSRemotingProtocolVersion      2.3   

Major  Minor  Build  Revision

---

10     0      10240  0       

I could get past the first exception by setting $filter t= "*" - that may or may not be clever, but then the exception regarding the SearchBase being empty: Gett-ADUser : An empty SearchBase is only supported while connected to a GlobalCatalog.

**Comment by ashsabet** [comment]
Hi Kelly, I responded to you directly via email.  I'm going to close this for now.
